development:
  adapter: postgresql
  encoding: unicode
  database: grifter_development
  host: localhost
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: grifter_test
  host: localhost
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: grifter_production
  host: localhost
  pool: 5
  username:
  password:
