development:
  adapter: postgis
  encoding: unicode
  postgis_extension: true
  schema_search_path: public,postgis
  pool: 5
  database: grifter_development
  host: localhost
  username:
  password:

test:
  adapter: postgis
  encoding: unicode
  postgis_extension: true
  schema_search_path: public,postgis
  pool: 5
  database: grifter_test
  host: localhost
  username:
  password:

production:
  adapter: postgis
  encoding: unicode
  postgis_extension: true
  schema_search_path: public,postgis
  pool: 5
  database: grifter_production
  host: localhost
  username:
  password:
